### ISSUE TITLE
10.14.6版本可以，11.1不行

### ISSUE THREAD

**Issue by xbyjava** [THLIVSQAZ/ACER-E5-471G-OpenCore#5]
您好，不知你还会不会更新这个，我现在用这个oc装10.14.6版本的可以，但是装您提到的11.1不行，可以解答下吗？或者可以提供11.1可以安装的镜像吗？

**Comment by THLIVSQAZ** [comment]
可以啊，截图就是11，镜像用黑果小兵即可
